kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
      templates:
      - '/etc/alertmanager/*.tmpl'
    route:
      receiver: alert-emailer
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 30m
      routes:
      - receiver: alert-emailer
        match:
          severity: critical
        group_wait: 10s
        repeat_interval: 1m

    receivers:
    - name: alert-emailer
      email_configs:
      - to: dridilotfi01@gmail.com
        send_resolved: false
        from: alertmanager@email.com
        smarthost: smtp.gmail.com:587
        require_tls: true
